# _config.yml - CONFIGURADO PARA DOMÍNIO PERSONALIZADO

title: O Meu Site de Matérias
description: "Um site para publicar textos e fotos sobre meus interesses."
# Para domínios personalizados, baseurl deve ser vazio
baseurl: ""
# URL principal do seu site
url: "https://geociencias.site"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

collections:
  posts:
    output: true
    permalink: /:title/
