# _config.yml

title: O Meu Site de Matérias
description: "Um site para publicar textos e fotos sobre meus interesses."
baseurl: "" # Mantenha vazio se o repositório for nomeado seu-usuario.github.io
url: "https://dmorocode.github.io" # Substitua 'seu-usuario'

# Build settings
markdown: kramdown
theme: minima # Você pode remover isso se quiser um estilo 100% customizado
plugins:
  - jekyll-feed

# Coleção para as matérias que o Decap CMS irá gerenciar
collections:
  posts:
    output: true
    permalink: /:title/
