# admin/config.yml - VERSÃO FINAL E CORRIGIDA

backend:
  name: github
  repo: "dmorocode/geociencias"
  branch: main
  # A linha abaixo força o uso do fluxo de autenticação correto do GitHub
  auth_endpoint: https://decap-cms-github-oauth-provider-z34m.onrender.com

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "posts"
    label: "Matérias"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Data de Publicação", name: "date", widget: "datetime" }
      - { label: "Imagem de Destaque", name: "image", widget: "image", required: false }
      - { label: "Conteúdo da Matéria", name: "body", widget: "markdown" }
