<<<<<<< HEAD
# admin/config.yml

# Backend: onde o conteúdo será salvo. Neste caso, o seu repositório GitHub.
backend:
  name: github
  repo: dmoroce/geociencias.github.io # IMPORTANTE: Substitua com seu usuário/repositório
  branch: main # ou master, dependendo da sua branch principal

# Onde as imagens que você subir serão salvas
media_folder: "assets/images"
public_folder: "/assets/images"

# Coleções: Define os tipos de conteúdo que você pode criar.
# Aqui, estamos definindo "Matérias".
collections:
  - name: "posts" # Deve ser o mesmo nome da coleção no _config.yml
    label: "Matérias" # O nome que aparecerá no painel
    folder: "_posts" # A pasta onde os arquivos serão salvos
    create: true # Permite criar novos arquivos
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Formato do nome do arquivo
    fields: # Os campos que você preencherá para cada matéria
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Data de Publicação", name: "date", widget: "datetime" }
      - { label: "Imagem de Destaque", name: "image", widget: "image", required: false }
      - { label: "Conteúdo da Matéria", name: "body", widget: "markdown" }
=======
